version: 2
updates:
    - directory: frontend
      open-pull-requests-limit: 2
      package-ecosystem: npm
      rebase-strategy: auto
      schedule:
          interval: 'daily'
    - directory: symfony
      open-pull-requests-limit: 2
      package-ecosystem: composer
      rebase-strategy: auto
      schedule:
          interval: 'daily'
