version: 2
updates:
  - directory: frontend
    open-pull-requests-limit: 5
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      interval: "weekly"
  - directory: symfony
    open-pull-requests-limit: 5
    package-ecosystem: composer
    rebase-strategy: auto
    schedule:
      interval: "weekly"