version: '3.7'

services:
    db:
        image: mariadb:10
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - './build/dbdata:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8081:80
        user: ${CURRENT_USER}
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - PMA_USER=${MYSQL_USER}
            - PMA_PASSWORD=${MYSQL_PASSWORD}
        depends_on:
            - db
    symfony:
        container_name: symfony
        build:
            context: .
            dockerfile: ./build/symfony/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        user: ${CURRENT_USER}
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./symfony:/var/www
            - /var/www/vendor
        depends_on:
            - db
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: ./build/nginx/Dockerfile
        volumes:
            - ./symfony:/var/www
            - ./frontend/dist:/var/www/public/dist
        ports:
            - 8080:80
            - 3001:3001
        depends_on:
            - symfony
            - vue
    vue:
        container_name: vue
        build:
            context: .
            dockerfile: ./build/vue/Dockerfile
        volumes:
            - ./frontend:/var/www
            - /var/www/node_modules
        ports:
            - 3000:3000
