version: '3.7'

services:
    db:
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - './mysql:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony
    symfony:
        build:
            context: .
            dockerfile: ./build/symfony/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
        environment:
            APP_ENV: dev
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./symfony:/code/symfony
            - /code/symfony/vendor
        networks:
            - symfony
        depends_on:
            - db
        user: ${USER_ID:-0}:${GROUP_ID:-0}
    nginx:
        build:
            context: .
            dockerfile: ./build/nginx/Dockerfile
        volumes:
            - ./symfony:/code/symfony
            - ./nginx:/var/logs/nginx
            - ./frontend/dist:/app/dist
        ports:
            - 8080:80
            - 3001:3001
        networks:
            - symfony
    vue:
        build:
            context: .
            dockerfile: ./build/vue/Dockerfile
            args:
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - 3000:3000
        networks:
            - symfony
        user: ${USER_ID:-0}:${GROUP_ID:-0}
networks:
    symfony:
