version: '3.7'

services:
    db:
        image: mariadb:10
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - './dbdata:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8081:80
        environment:
            - PMA_ARBITRARY=1 
            - PMA_HOST=db
            - PMA_USER=${MYSQL_USER}
            - PMA_PASSWORD=${MYSQL_PASSWORD}
        networks:
            - symfony
        depends_on:
            - db
    symfony:
        container_name: symfony
        build:
            context: .
            dockerfile: ./build/symfony/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        environment:
            APP_ENV: dev
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./symfony:/var/www 
        networks:
            - symfony
        depends_on:
            - db
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: ./build/nginx/Dockerfile
        volumes:
            - ./symfony:/var/www
            - ./nginx/logs:/var/logs/nginx
            - ./frontend/dist:/var/www/public/dist
        ports:
            - 8080:80
            - 3001:3001
        networks:
            - symfony
        depends_on:
            - symfony
            - vue
    vue:
        container_name: vue
        build:
            context: .
            dockerfile: ./build/vue/Dockerfile
        volumes:
            - ./frontend/code:/var/www/code  
        ports:
            - 3000:3000
        networks:
            - symfony
networks:
    symfony:
