# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        # When a handler class is able to handle a given command object on the bus,
        # Symfony will deal with invoking the handler for us.
        App\Application\Command\Interface\Handler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

    # makes classes in src/App/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App/'
        exclude:
            - '../src/App/DependencyInjection/'
            - '../src/App/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/App/Controller/'
        tags: ['controller.service_arguments']

    # This is were our infrastructure, application and domain code resides in
    Productivity\:
        resource: '../src/Productivity/'

    # Wire up interfaces

    Productivity\Todo\Infrastructure\DbalTodoRepository: ~

    Productivity\Todo\Domain\TodoRepositoryInterface: '@Productivity\Todo\Infrastructure\DbalTodoRepository'
